# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LlXYshyY0YMAoi9HQSfl20C2S2NM6Dzkh6TANvBYUojVGW3Y67FxAFE7pZZMM6KXt+GJr9eDLNb16ywZJEa66qFczzCFAlaeFTSLbJiiLPWi9KLFfnBaUPxxxmS6Zaw3gvyLDg4QECA6aBzpYAmmHq2YU7ZtotmEf7bpjkVde/oGMSZtZhOf5LpzEbtn9lGhOpwGGEdW8X15alBLPYAvf1M49AUfb05UjzSVp3oGFevoOgQUBEV7LBmqYZd7/6TRSdCQlEo6EhQMlvFyVLpzW7ln/V7h8QCKiVnT7TJKaN4Nt69rB8S7wboDyjUpjNYjKjh+kO2H94YvsFHk1iEpXb11cdSUrRqfZmCuIuaNwn9+cMPiwsxpqraqWHZTqTp/McyhDx2w9G3NIl9Zh1NBuv5sta9aknQdBS6Cxtd9QDnDnATNRiZJpfpK2Wj8kKNjpBYhNF+hBUhvD8yKI2hva8lgZ6wn99FU14MA09f2+2WrGTNdkonhjfOGyNi30KWEBwQ0jhvAkQgRNfKfwDU/csVCJ4sHUrjyyOZSexN1og/N3DcLcBhbUEjtKI1YO+o97R1+JhjnR3gCMwmM1KQheng87IGnZxlTdD+u5aE1nt2vliSz47AnQLbRIYQqvLCSf1Qu9v1aQyBlRHkYYWNXzxzR80SEjgA18UifzcCUwOo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
