appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LlXYshyY0YMAoi9HQSfl20C2S2NM6Dzkh6TANvBYUojVGW3Y67FxAFE7pZZMM6KXt+GJr9eDLNb16ywZJEa66qFczzCFAlaeFTSLbJiiLPWi9KLFfnBaUPxxxmS6Zaw3gvyLDg4QECA6aBzpYAmmHq2YU7ZtotmEf7bpjkVde/oGMSZtZhOf5LpzEbtn9lGhOpwGGEdW8X15alBLPYAvf1M49AUfb05UjzSVp3oGFevoOgQUBEV7LBmqYZd7/6TRSdCQlEo6EhQMlvFyVLpzW7ln/V7h8QCKiVnT7TJKaN4Nt69rB8S7wboDyjUpjNYjKjh+kO2H94YvsFHk1iEpXb11cdSUrRqfZmCuIuaNwn9+cMPiwsxpqraqWHZTqTp/McyhDx2w9G3NIl9Zh1NBuv5sta9aknQdBS6Cxtd9QDnDnATNRiZJpfpK2Wj8kKNjpBYhNF+hBUhvD8yKI2hva8lgZ6wn99FU14MA09f2+2WrGTNdkonhjfOGyNi30KWEBwQ0jhvAkQgRNfKfwDU/csVCJ4sHUrjyyOZSexN1og/N3DcLcBhbUEjtKI1YO+o97R1+JhjnR3gCMwmM1KQheng87IGnZxlTdD+u5aE1nt2vliSz47AnQLbRIYQqvLCSf1Qu9v1aQyBlRHkYYWNXzxzR80SEjgA18UifzcCUwOo=}
